language: rust
matrix:
  include:
    - rust: 1.40.0
    - rust: stable
    - rust: nightly
      script:
        - cargo bench
cache:
  directories:
  - $HOME/.cargo
  - ./target # OK to cache because `cargo` will pick up changes to the project.
script:
  - cargo test
